export const SCRIPT_TEXT_HTML = `\`\`\`html
<script type="text/html">
    <div>
        <span></span>
    </div>
</script>
\`\`\``;

export const SVELTE_HTML = `\`\`\`html
<script>
	let name = 'lyl';
</script>

<h1>Hello {name.toUpperCase()}!</h1>
\`\`\``;

export const SVELTE = `\`\`\`js
/* App.svelte generated by Svelte v3.56.0 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "svelte/internal";

function create_fragment(ctx) {
	let h1;

	return {
		c() {
			h1 = element("h1");
			h1.textContent = \`Hello \${name.toUpperCase()}!\`;
		},
		m(target, anchor) {
			insert(target, h1, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(h1);
		}
	};
}

let name = 'lyl';

class App extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default App;
\`\`\``;

export const CODE = `\`\`\`js
var a=0;
a="hello";
console.log(a); // hello
a++; 
console.log(a); //NaN
\`\`\``;
